### ISSUE TITLE
Problems when pip install

### ISSUE THREAD

**Issue by breoganpardo** [astrojuanlu/ie-mbd-advanced-python#55] opened 2019-04-07 09:36 UTC
Hello professor,
I am redoing all we have done in class this week. So I have created again a folder with the structure provided (src, tests, ...) when I am done, I try to do pip install ie_nlp_utils (name provided in metadata of  setup.cfg) and I find this error:
![image](https://user-images.githubusercontent.com/44050530/55681669-579dc780-5929-11e9-9965-270fbd31b2d1.png)

By the way, in this case I called the package and the name in setup.cfg ie_nlp_utils, the same exactly name.
What am I doing wrong?

**Comment by astrojuanlu** [comment] 2019-04-07 10:56
Hi @breoganpardo! The problem is that, when you do that, pip tries to find https://pypi.org/project/ie_nlp_utils/, which doesn't exist. The correct way of doing it is to specify the path *in your computer* where your `setup.{py,cfg}` are:

```
$ pip install ~/GitHub_projects/breo_package/
```

(assuming you have your `setup` files there). This is why we normally do `pip install .`, which means "install the current directory".

Please test if it works, and if it does you can close the issue!

**Comment by breoganpardo** [comment] 2019-04-07 11:08
It worked!
![image](https://user-images.githubusercontent.com/44050530/55682608-31caef80-5936-11e9-8a1e-ca27ead7cae8.png)
Thank you very much!

**Comment by breoganpardo** [comment] 2019-04-07 11:35
Hello professor,
The pip install is working. Then I go to python and import, it works. However, when I try to use the simple function within the __init__.py:
```
print('Hello world')

def sum_numbers():
        return 4
```

It seems like it does not find it:
![image](https://user-images.githubusercontent.com/44050530/55682912-f03c4380-5939-11e9-976a-14420486f67d.png)

![image](https://user-images.githubusercontent.com/44050530/55682907-df8bcd80-5939-11e9-99e5-6382b62d2bc6.png)

**Comment by astrojuanlu** [comment] 2019-04-07 11:41
You have to choose between two options:

```python
from ie_nlp_utils import sum_numbers

sum_numbers(a, b)
```

or:

```python
import ie_nlp_utils

ie_nlp_utils.sum_numbers(a, b)
```

**Closed as completed** 2019-04-08 17:08 UTC
